---

- hosts: keystone-server
  roles:
     - role: keystone
       keystone_tenants:
         - { name: admin, description: "Admin Project" }
         - { name: service, description: "Service Project" }
         - { name: demo, description: "Demo Project" }
       keystone_users:
         - { name: admin, password: "{{ ADMIN_USER_PASS }}", tenant: admin }
         - { name: demo, password: "{{ DEMO_USER_PASS }}", tenant: demo }
         - { name: keystone, password: "{{ KEYSTONE_USER_PASS }}", tenant: service }
       keystone_roles:
         - { name: admin, user: admin, tenant: admin }
         - { name: _member_, user: demo, tenant: demo  }
         - { name: admin, user: keystone, tenant: service  }
