---

#
# Install Keystone
#

- name: install keystone application and dependencies
  apt: name="{{ item }}" state=present
  with_items:
    - keystone
    - python-openstackclient
    - apache2
    - libapache2-mod-wsgi
    - memcached
    - python-memcache
  become: yes
  become_method: sudo
  environment:
    http_proxy: {{ HTTP_PROXY }}
